baseurl = "http://www.premioartecultura.it"
# theme = "tablemania"
theme = "gohugo-theme-ananke"
title = "Premio Arte e Cultura 'La Bagnaia'"
[permalinks]
  page = "/:year/:slug/"
[menu]
  [[menu.archive]]
    identifier = "2018"
    name = "2018"
    url = "/2018/"
  [[menu.archive]]
    identifier = "2015"
    name = "2015"
    url = "/2015/"
  [[menu.archive]]
    identifier = "2013"
    name = "2013"
    url = "/2013/"
  [[menu.archive]]
    identifier = "2011"
     name = "2011"
     url = "/2011/"
  [[menu.archive]]
    identifier = "2009"
    name = "2009"
    url = "/2009/"
  [[menu.archive]]
    identifier = "2008"
    name = "2008"
    url = "/2008/"
  [[menu.archive]]
    identifier = "2007"
    name = "2007"
    url = "/2007/"
  [[menu.archive]]
    identifier = "2006"
    name = "2006"
    url = "/2006/"
  [[menu.archive]]
    identifier = "2005"
    name = "2005"
    url = "/2005/"
  [[menu.archive]]
    identifier = "2004"
    name = "2004"
    url = "/2004/"
  [[menu.archive]]
    identifier = "2003"
    name = "2003"
    url = "/2003/"

